#!/bin/bash
while true; do
  curl -s http://lul-trackernet.tfl.gov.uk/TrackernetWebService/TimetableService.aspx\?Feed\=4\&Line\=D\&Time\= | xmllint --format - | grep -i $*
  echo $(date)
  echo ''
  sleep 10
done
